"""create tool calls table

Revision ID: 586344b8ad35
Revises: faf61fe473ea
Create Date: 2026-07-26 15:56:23.675625
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '586344b8ad35'
down_revision: str | None = 'faf61fe473ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('requested_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='toolexecutionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('validation_status', sa.Enum('not_attempted', 'passed', 'failed', name='toolvalidationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('failure_type', sa.Enum('unsupported_tool', 'validation_error', 'not_found', 'database_error', 'execution_error', name='toolfailuretype', native_enum=False, length=30), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_conversation_id'), 'tool_calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_message_id'), 'tool_calls', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_message_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_conversation_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    # ### end Alembic commands ###
